# -*- coding: utf-8 -*-
"""Solar Irradiation Despliegue.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zYzHmJdaM9GIocGB27qxFe6nnhGAyf44

# Despliegue

- Cargamos el modelo
- Cargamos los datos futuros
- Preparamos los datos futuros
- Aplicamos el modelo para la predicción
"""

# Importamos librerías basicas

import pandas as pd # Dataframes
import numpy as np # Matrices y vectores
import matplotlib.pyplot as plt #Graficas

#Cargamos el modelo
import pickle
filename = "modelo.pkl"

modelo, labelEncoder, variables = pickle.load(open(filename, 'rb'))

# Modelo, labelEncoder, variables, min_max_scaler

# Cargamos los datos futuros
# data = pd.read_csv("Datos_irradiancia_Solar_Futuros.csv")
# data.head()

"""## **Calidad del modelo**

1. Exactitud: 87%
2. Precisión: 84%
3. Recall: 84%
4. f1-score: 84%
"""

# Aquí va la interfaz grafica
import streamlit as st

st.title("Predicción de irradiancia solar")

with st.form("Formulario para la predicción"):
  st.subheader("Hora y Mes")

  # Hora
  hora_options = {
      "12:00 AM": 0, "1:00 AM": 1, "2:00 AM": 2, "3:00 AM": 3,
      "4:00 AM": 4, "5:00 AM": 5, "6:00 AM": 6, "7:00 AM": 7,
      "8:00 AM": 8, "9:00 AM": 9, "10:00 AM": 10, "11:00 AM": 11,
      "12:00 PM": 12, "1:00 PM": 13, "2:00 PM": 14, "3:00 PM": 15,
      "4:00 PM": 16, "5:00 PM": 17, "6:00 PM": 18, "7:00 PM": 19,
      "8:00 PM": 20, "9:00 PM": 21, "10:00 PM": 22, "11:00 PM": 23
  }

  hora_display = st.selectbox("Hora", list(hora_options.keys()))
  hora = hora_options[hora_display]

  # Mes
  mes_options = {
      "Enero": 1, "Febrero": 2, "Marzo": 3, "Abril": 4,
      "Mayo": 5, "Junio": 6, "Julio": 7, "Agosto": 8,
      "Septiembre": 9, "Octubre": 10, "Noviembre": 11, "Diciembre": 12
  }

  mes_display = st.selectbox("Mes", list(mes_options.keys()))
  mes = mes_options[mes_display]

  # Es Nocturno

  es_nocturno_value = 1 if hora > 6 and hora < 18 else 0

  st.divider()

  st.subheader("Temperatura y precipitación")

  # Temperatura
  temperature = st.slider(
      "Temperatura (°C)",
      min_value=-26,
      max_value=40,
      value=20,
      step=1,
  )

  # Precipitación
  precipitation_total = st.slider(
      "Precipitación Total (mm)",
      min_value=0.0,
      max_value=20.0,
      value=0.0,
      step=0.1,
  )

  st.divider()

  st.subheader("Humedad")

  # Humedad
  relative_humidity = st.slider(
      "Humedad Relativa (%)",
      min_value=0,
      max_value=100,
      value=50,
      step=1,
  )

  st.divider()

  st.subheader("Cobertura de nubes")

  st.write("Nota: Las coberturas por nivel (Alta, Media, Baja) deben ser menores o iguales a la cobertura total.")

  # Cobertura total de nubes
  cloud_cover_total = st.slider(
      "Cobertura Total de Nubes (%)",
      min_value=0,
      max_value=100,
      value=50,
      step=1,
  )

  # Cobertura en altura alta
  cloud_cover_high = st.slider(
      "Nubes Altas (%)",
      min_value=0,
      max_value=cloud_cover_total,  # Limitado por total
      value=min(20, cloud_cover_total),
      step=1,
      help="Cobertura de nubes a gran altitud"
  )

  # Cobertura en altura media
  cloud_cover_medium = st.slider(
      "Nubes Medias (%)",
      min_value=0,
      max_value=cloud_cover_total,  # Limitado por total
      value=min(20, cloud_cover_total),
      step=1,
      help="Cobertura de nubes a altitud media"
  )

  # Cobertura en altura baja
  cloud_cover_low = st.slider(
      "Nubes Bajas (%)",
      min_value=0,
      max_value=cloud_cover_total,  # Limitado por total
      value=min(10, cloud_cover_total),
      step=1,
      help="Cobertura de nubes a baja altitud"
  )

  suma_nubes = cloud_cover_high + cloud_cover_medium + cloud_cover_low

  st.divider()

  submitted = st.form_submit_button("Realizar Predicción", use_container_width=True)

if submitted:
  #Validación de la suma de las nubes
  if suma_nubes > cloud_cover_total:
    st.error("No se puede realizar la predicción. La suma de coberturas por nivel no puede exceder la cobertura total.")
  else:

    datos_input = {
        'Hora': hora,
        'Mes': mes,
        'Es_nocturno': es_nocturno_value,
        'Temperature': temperature,
        'Precipitation_Total': precipitation_total,
        'Relative_Humidity': relative_humidity,
        'Cloud_Cover_Total': cloud_cover_total,
        'Cloud_Cover_High': cloud_cover_high,
        'Cloud_Cover_Medium': cloud_cover_medium,
        'Cloud_Cover_Low': cloud_cover_low
    }

    data = pd.DataFrame([datos_input])

    # Preparación de los datos
    data_preparada = data.copy()
    data_preparada = pd.get_dummies(data, columns=['Hora', 'Mes', 'Es_nocturno'], drop_first=False, dtype=int) # Para despliegue siempre drop en falso
    data_preparada.head()

    # Adicionamos las columnas faltantes
    data_preparada = data_preparada.reindex(columns=variables, fill_value=0)
    data_preparada.head()

    # Hacemos la predicción del modelo
    Y_fut = modelo.predict(data_preparada)
    print(Y_fut)

    # Almacenamos la predicción revirtiendo el labelEncoder
    data["Prediccion"] = labelEncoder.inverse_transform(Y_fut)
    data.head()

    st.header("Predicción: ")

    data